spring:
  datasource:
#    Example where a wallet is used (TNS_ADMIN is the location of the wallet).
#     Eg if using Oracle Cloud ADB (autonomous database) Always Free.
#    url: "jdbc:oracle:thin:@xr_tp?TNS_ADMIN=/Users/me/Wallet_mydb"
#   Example without wallet.  Eg if using Oracle 23c Free.
#    url: "jdbc:oracle:thin:@localhost:1521/freepdb1"
    url: jdbc:oracle:thin:@mydb_tp?TNS_ADMIN=/Users/me/Wallet_mydb
    #   Use "admin" for username for setup with Oracle Cloud ADB
    #    and use "sys as sysdba" for username for setup with Oracle 23c Free
    username: GeoCacheUser
    password: Welcome12345
    driver-class-name: oracle.jdbc.OracleDriver
    type: oracle.ucp.jdbc.PoolDataSource
    oracleucp:
      connection-factory-class-name: oracle.jdbc.pool.OracleDataSource
